@startuml
'https://plantuml.com/class-diagram
class PeopleList{
    Person: PeopleList

    readInPeople()
    sortPeople()
    printPeople()
}
class Person{
    String firstName
    String lastName
    int salary

    readPerson()
    getFirstName()
    getLastName()
    getSalary()

}

PeopleList->Person
@enduml