@startuml
'https://plantuml.com/class-diagram

class FrequencyFinder(){
String textStr
Word: WordList

findWordsFrequency()

addFrequencyToWord()

addWord()

displayHistogram()
}

class Word(){
String word
int frequency
}

@enduml